"""
bootstrap.py — Workspace initialization and bootstrapping for Supervisor V34 (Headless).

Responsible for setting up the isolated `.ag-supervisor/` directory
and generating project-level metadata files like SUPERVISOR_MANDATE.md
and AGENTS.md.

V34: Removed open_browser.ps1 generation — no longer needed in headless architecture.
"""

import logging
from datetime import datetime
from pathlib import Path

from . import config

logger = logging.getLogger("supervisor")

def bootstrap_workspace(project_path: str, goal: str) -> None:
    """
    Ensure the local supervisor environment is initialized.
    Creates state directory and writes MANDATE and AGENTS files.
    """
    # 1. Ensure the project is set and state dir exists
    config.set_project_path(project_path)
    state_dir = config.get_state_dir()

    # 2. Write SUPERVISOR_MANDATE.md (To the root for maximum visibility)
    mandate_path = Path(project_path) / config.MANDATE_FILENAME
    mandate_content = f"""# 🤖 SUPERVISOR MANDATE

> **Auto-generated by Supervisor AI. The Agent MUST read and execute ALL instructions below.**

---

## ULTIMATE DIRECTIVE

{config.ULTIMATE_MANDATE}

---

## YOUR MISSION

{goal}

---

## OPERATING RULES

1. Complete this mission FULLY and AUTONOMOUSLY — do not ask questions, use your best judgment.
2. On FIRST RUN: audit the entire project, review all main flows, fix any broken state, and build a comprehensive overview before making new changes.
3. Start the dev server at any available port.
4. Run all tests autonomously via shell commands. If tests fail, fix the code.
5. Check for syntax errors, lint warnings, and type errors using language-appropriate tools.
6. Use the latest 2026-era tools, libraries, and best practices. Push every aspect to perfection.
7. After every meaningful change, update `PROJECT_STATE.md` in the project root with:
   - **What was built** — completed features and changes
   - **What needs improvement** — known quality gaps
   - **Bugs** — any issues discovered
   - **Required features** — what still needs to be implemented
   - **Design notes** — UI/UX improvements and architectural decisions
   - **Test results** — what was tested and the outcome
   - **Next steps** — what to work on next
8. If `PROJECT_STATE.md` does not exist, create it immediately with the current project assessment.

---

*Generated at: {datetime.now().isoformat()}*
"""
    mandate_path.write_text(mandate_content, encoding="utf-8")
    logger.info("📄  Wrote SUPERVISOR_MANDATE.md to: %s", mandate_path)
    print(f"  📄 Created: {mandate_path}")

    # 3. Write AGENTS.md into the isolated .ag-supervisor/ directory
    agents_path = state_dir / "AGENTS.md"
    if not agents_path.exists():
        agents_content = """# Agent Council Personas

This file defines the specialized personas used by the Agent Council
for this specific project. It allows you to tailor the experts
evaluating blocked scenarios.

## Example Personas

- **The Architect**: Focuses on structural integrity and design patterns.
- **The Debugger**: Focuses on raw stack traces and variable states.
- **The Critic**: Devil's advocate, looking for flaws in the proposed plan.

*You can edit this file to add or remove personas.*
"""
        agents_path.write_text(agents_content, encoding="utf-8")
        logger.info("👥  Created AGENTS.md in isolated state dir: %s", agents_path)
        print(f"  👥 Created: {agents_path}")

