"""
bootstrap.py — Workspace initialization and bootstrapping for Supervisor V34 (Headless).

Responsible for setting up the isolated `.ag-supervisor/` directory
and generating project-level metadata files like SUPERVISOR_MANDATE.md
and AGENTS.md.

V34: Removed open_browser.ps1 generation — no longer needed in headless architecture.
"""

import logging
from datetime import datetime, timezone
from pathlib import Path

from . import config

logger = logging.getLogger("supervisor")

def bootstrap_workspace(project_path: str, goal: str) -> None:
    """
    Ensure the local supervisor environment is initialized.
    Creates state directory and writes MANDATE and AGENTS files.
    """
    # 1. Ensure the project is set and state dir exists
    config.set_project_path(project_path)
    state_dir = config.get_state_dir()

    # 2. Write SUPERVISOR_MANDATE.md (To the root for maximum visibility)
    mandate_path = Path(project_path) / config.MANDATE_FILENAME
    mandate_content = f"""# 🤖 SUPERVISOR MANDATE

> **Auto-generated by Supervisor AI. The Agent MUST read and execute ALL instructions below.**

---

## ULTIMATE DIRECTIVE

{config.ULTIMATE_MANDATE}

---

## YOUR MISSION

{goal}

---

## OPERATING RULES

1. Complete this mission FULLY and AUTONOMOUSLY — do not ask questions, use your best judgment.
2. On FIRST RUN: audit the entire project, review all main flows, fix any broken state, and build a comprehensive overview before making new changes.
3. Start the dev server at any available port.
4. Run all tests autonomously via shell commands. If tests fail, fix the code.
5. Check for syntax errors, lint warnings, and type errors using language-appropriate tools.
6. Use the latest 2026-era tools, libraries, and best practices. Push every aspect to perfection.
7. After every meaningful change, update `PROJECT_STATE.md` in the project root with:
   - **What was built** — completed features and changes
   - **What needs improvement** — known quality gaps
   - **Bugs** — any issues discovered
   - **Required features** — what still needs to be implemented
   - **Design notes** — UI/UX improvements and architectural decisions
   - **Test results** — what was tested and the outcome
   - **Next steps** — what to work on next
8. If `PROJECT_STATE.md` does not exist, create it immediately with the current project assessment.

---

*Generated at: {datetime.now(timezone.utc).isoformat()}*
"""
    mandate_path.write_text(mandate_content, encoding="utf-8")
    logger.info("📄  Wrote SUPERVISOR_MANDATE.md to: %s", mandate_path)
    print(f"  📄 Created: {mandate_path}")

    # ── NOTE-SAFE: Re-append any saved context notes so they survive overwrites ──
    # context_notes.json is the authoritative store — SUPERVISOR_MANDATE.md is derived.
    # This must run AFTER every write to the mandate so notes are NEVER silently lost.
    _notes_path = Path(project_path) / ".ag-supervisor" / "context_notes.json"
    if _notes_path.exists():
        try:
            import json as _json
            _notes = _json.loads(_notes_path.read_text(encoding="utf-8"))
            if _notes:
                _current = mandate_path.read_text(encoding="utf-8")
                # Strip any stale notes block already present (avoid double-append)
                _cutoff = _current.find("\n\n## Persistent Context Notes")
                if _cutoff != -1:
                    _current = _current[:_cutoff]
                _lines = ["\n\n## Persistent Context Notes\n\n"]
                for _i, _n in enumerate(_notes, 1):
                    _lines.append(f"{_i}. {_n['text']}\n")
                mandate_path.write_text(_current + "".join(_lines), encoding="utf-8")
                logger.info(
                    "📌  [Bootstrap] Re-appended %d context note(s) to SUPERVISOR_MANDATE.md",
                    len(_notes),
                )
        except Exception as _nex:
            logger.warning("📌  [Bootstrap] Could not re-append notes (non-fatal): %s", _nex)


    # V56: VISION.md section
    _vision_section = ""
    _vision_path = Path(project_path) / "VISION.md"
    if _vision_path.exists():
        try:
            _vision_text = _vision_path.read_text(encoding="utf-8")[:3000]
            _vision_section = f"\n## Project Vision\n\n{_vision_text}\n"
        except Exception:
            pass

    # V69: Load research.md via @-file reference — the CLI expands these
    # natively when reading GEMINI.md, keeping the file small (~2K vs 200K)
    # and ensuring research stays up-to-date on every task launch.
    _research_section = ""
    for _rname in ("research.md", "RESEARCH.md"):
        _rpath = Path(project_path) / _rname
        if _rpath.exists():
            _research_section = (
                f"\n## Research Findings (Authoritative — shapes all tasks)\n\n"
                f"@{_rname}\n"
            )
            logger.info("📄  bootstrap: using @%s reference in GEMINI.md (avoids 200K inline)", _rname)
            break

    # V60: Load DEEP_ANALYSIS.md if present — pre-build risk analysis from the
    # background analysis pass. Every worker task benefits from these findings.
    _deep_analysis_section = ""
    _da_path = Path(project_path) / ".ag-supervisor" / "DEEP_ANALYSIS.md"
    if _da_path.exists():
        try:
            _da_text = _da_path.read_text(encoding="utf-8")[:4000]
            _deep_analysis_section = (
                f"\n## Pre-Build Risk Analysis (Read Before Starting Any Task)\n\n"
                f"{_da_text}\n"
            )
            logger.info("📄  bootstrap: injected DEEP_ANALYSIS.md (%d chars) into GEMINI.md", len(_da_text))
        except Exception:
            pass

    gemini_md_path = Path(project_path) / "GEMINI.md"
    gemini_md_content = f"""# Supervisor AI — Project Context

> Auto-generated by Supervisor AI. Do NOT edit manually — it is overwritten on each launch.
> For persistent project notes, see `SUPERVISOR_MANDATE.md`.

## Mission

{goal}
{_vision_section}{_research_section}{_deep_analysis_section}
## Code Quality Rules (apply to EVERY task)

- **No stubs or TODOs**: Every function must be fully implemented. Never leave `pass`, `// TODO`, or placeholder returns.
- **No console.log**: Remove all debug logging before completing a task (`console.log`, `print()`, `debugger`).
- **No hardcoded values**: Use constants, env vars, or config files. Never hardcode ports, API keys, or URLs.
- **TypeScript strict**: If this is a TS project, aim for zero `tsc --noEmit` errors. Do not use `any` or `@ts-ignore` without justification.
- **No dead code**: Remove unused imports, variables, functions, and components.
- **Tests**: Run tests before marking a task done. If tests fail, fix them.
- **Latest libs**: Always verify latest stable version of any package before adding it. Never use version ranges.
- **Config verification**: Before writing or modifying ANY build tool config (vite.config, eslint.config, tailwind.config, tsconfig, next.config, postcss.config, webpack.config), first run `npm ls <tool>` to check the installed version, then look up the official docs or migration guide for THAT version. Your training data may contain deprecated patterns (e.g. Vite esbuild → oxc, ESLint .eslintrc → flat config). Always match the config schema to the installed version.
- **Scaffolding verification**: Before running ANY `npx create-*` or `npm init` scaffolding command, run it with `--help` first. CLI flags change between versions — using old flags causes misconfigurations or failures. Always initialize in the current directory with `./`.
- **Framework API verification**: When using a major framework feature for the first time in a project (React hooks, Next.js routing, Vue composables, Tailwind classes), run `npm ls <framework>` and verify you're using the API for THAT version. Key breaking changes to watch: React 19 `use()` hook, Next.js 15 Server Components (no more getServerSideProps), Tailwind v4 CSS-based config (no tailwind.config.js), ESLint 9+ flat config. When in doubt, search the official docs.

## File Edit Protocol (MANDATORY — V58 Layer 5)

When modifying an EXISTING file, you MUST use the SEARCH/REPLACE format below.
This prevents content from being accidentally overwritten when parallel tasks run.

Format for each change block:
```
<<<SEARCH
[exact existing lines to find — must be unique in the file]
=====
[replacement lines — what to put there instead]
REPLACE>>>
```

Rules:
- SEARCH must be an exact match (whitespace included) of lines currently in the file
- One block per logical change — keep blocks small and targeted
- For additions with no replacement, use an empty SEARCH block:
  ```
  <<<SEARCH
  =====
  [new lines to insert at end of file or after a known anchor]
  REPLACE>>>
  ```
- For NEW files (don't exist yet), just write them directly — no SEARCH/REPLACE needed
- Never write out the entire file if you are only changing a small part of it

## Windows Compatibility (MANDATORY)

The host OS is **Windows**. All projects must run natively on Windows without WSL.

**FORBIDDEN in package.json scripts, shell commands, or build tooling:**
- `head`, `tail`, `grep`, `sed`, `awk`, `cat`, `wc`, `tee` — not available on Windows
- `rm -rf` — use `rimraf` or `shx rm -rf` instead
- `cp -r` — use `shx cp -r` or `ncp` instead
- `chmod`, `chown`, `ln -s` — no-op or broken on Windows
- `export VAR=val` — use `cross-env VAR=val` instead
- `&&` chains with Linux commands — each segment must be Windows-safe
- Unix path separators in shell scripts (`/usr/bin/env`) — use `npx` or direct command

**Safe alternatives:**
- `rimraf` — cross-platform `rm -rf`
- `cross-env` — cross-platform environment variables
- `shx` — cross-platform shell commands (wraps ShellJS)
- `concurrently` or `npm-run-all` — cross-platform parallel/serial script running
- Node.js `fs` APIs — for any file manipulation in build scripts

## Architecture Conventions

- Read `PROJECT_STATE.md` (if it exists) for current project state before making changes.
- Read `SUPERVISOR_MANDATE.md` for the complete mission and all persistent context notes.
- After every meaningful change, update `PROJECT_STATE.md`.
- Emit `LOCAL_ACTION: npm_install` if you modify `package.json`.
- Emit `LOCAL_ACTION: clear_vite_cache` if you modify `tailwind.config.*` or `postcss.config.*`.
- Emit `DAG_INJECT: {{"tasks": [...]}}` if you discover additional work that should be queued as sub-tasks.

*Generated: {datetime.now(timezone.utc).isoformat()}*
"""
    gemini_md_path.write_text(gemini_md_content, encoding="utf-8")
    logger.info("📄  Wrote GEMINI.md to: %s", gemini_md_path)
    print(f"  📄 Created: {gemini_md_path}")

    # V41/V60: Always overwrite .gemini/settings.json to keep settings in sync.
    # V60 additions: inlineThinkingMode:full streams Gemini's thoughts so our
    # subprocess reader sees output during extended thinking — preventing false
    # inactivity-timeout kills.  checkpointing:true enables native CLI checkpointing.
    gemini_dir = Path(project_path) / ".gemini"
    gemini_dir.mkdir(parents=True, exist_ok=True)
    gemini_settings = gemini_dir / "settings.json"
    import json as _json
    _settings = {
        "timeout": 600000,          # 10 minutes in ms — matches our INACTIVITY_TIMEOUT
        "checkpointing": True,      # V60: Enable native CLI checkpointing
        "ui": {
            "inlineThinkingMode": "full",  # V60: Stream thoughts → prevents false timeout kills
            "showStatusInTitle": True,
        },
        "theme": "Default",
    }
    gemini_settings.write_text(_json.dumps(_settings, indent=2), encoding="utf-8")
    logger.info("⚙️  Wrote .gemini/settings.json (timeout=600s, inlineThinkingMode=full, checkpointing=True)")
    print(f"  ⚙️  Wrote: {gemini_settings}")

    # 3. Write AGENTS.md into the isolated .ag-supervisor/ directory
    agents_path = state_dir / "AGENTS.md"
    if not agents_path.exists():
        agents_content = """# Agent Council Personas

This file defines the specialized personas used by the Agent Council
for this specific project. It allows you to tailor the experts
evaluating blocked scenarios.

## Example Personas

- **The Architect**: Focuses on structural integrity and design patterns.
- **The Debugger**: Focuses on raw stack traces and variable states.
- **The Critic**: Devil's advocate, looking for flaws in the proposed plan.

*You can edit this file to add or remove personas.*
"""
        agents_path.write_text(agents_content, encoding="utf-8")
        logger.info("👥  Created AGENTS.md in isolated state dir: %s", agents_path)
        print(f"  👥 Created: {agents_path}")

    # 4. Write .gitignore if one doesn't already exist
    gitignore_path = Path(project_path) / ".gitignore"
    if not gitignore_path.exists():
        gitignore_content = """\
# ── Node.js ──────────────────────────────────────────
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnp/
.pnp.js
.yarn/install-state.gz

# ── Build outputs ────────────────────────────────────
dist/
build/
out/
.next/
.nuxt/
.vite/
*.tsbuildinfo

# ── Python ───────────────────────────────────────────
__pycache__/
*.py[cod]
*.pyo
.venv/
venv/
env/
.env/
*.egg-info/
dist/
.Python

# ── Environment & secrets ────────────────────────────
.env
.env.local
.env.*.local

# ── Supervisor AI state ──────────────────────────────
# (checkpoints, DAG state, session files — not source code)
.ag-supervisor/

# ── Editor & OS ──────────────────────────────────────
.DS_Store
Thumbs.db
.idea/
.vscode/
*.swp
*.swo
"""
        gitignore_path.write_text(gitignore_content, encoding="utf-8")
        logger.info("📄  Created .gitignore at: %s", gitignore_path)
        print(f"  📄 Created: {gitignore_path}")
    else:
        # Existing .gitignore — ensure .ag-supervisor/ is in it
        try:
            _gi_text = gitignore_path.read_text(encoding="utf-8")
            if ".ag-supervisor" not in _gi_text:
                with open(gitignore_path, "a", encoding="utf-8") as _gi_f:
                    _gi_f.write("\n# Supervisor AI state\n.ag-supervisor/\n")
                logger.info("📄  Appended .ag-supervisor/ to existing .gitignore")
        except Exception as _gi_exc:
            logger.debug("Could not update .gitignore: %s", _gi_exc)

    # V58: Layer 4 — git init guard.
    # All supervised projects must be git repos so per-task commits work.
    # `git init` is idempotent — safe to run even if repo already exists.
    try:
        import subprocess as _gsp
        _gi_res = _gsp.run(
            ["git", "-C", project_path, "rev-parse", "--is-inside-work-tree"],
            capture_output=True, timeout=5,
        )
        if _gi_res.returncode != 0:
            # Not a git repo — initialise one silently
            _gsp.run(
                ["git", "-C", project_path, "init", "--quiet"],
                capture_output=True, timeout=10,
            )
            _gsp.run(
                ["git", "-C", project_path, "config", "user.email", "supervisor@local"],
                capture_output=True, timeout=5,
            )
            _gsp.run(
                ["git", "-C", project_path, "config", "user.name", "Supervisor AI"],
                capture_output=True, timeout=5,
            )
            logger.info("🗂️  Initialised git repo in project: %s", project_path)
            print(f"  🗂️  git init: {project_path}")
    except Exception as _gexc:
        logger.debug("git init guard error (non-fatal): %s", _gexc)

