"""
cli_worker.py — V13 Omni-Brain Execution Layer (The Worker)

Responsible for routing complex execution objectives generated by the
Local Manager (Ollama) directly to the Gemini 3.1 Pro CLI.
"""

import asyncio
import logging
import subprocess
from typing import Optional

logger = logging.getLogger("supervisor.cli_worker")

class CLIWorker:
    """Invokes the Gemini CLI to execute complex file modifications."""

    def __init__(self, model: str = "gemini-2.5-pro", max_retries: int = 3):
        self.model = model
        self.max_retries = max_retries

    async def execute_objective(self, objective: str, cwd: str = ".") -> dict:
        """
        Feed the objective to the Gemini CLI.
        Uses --always-run to ensure silent, non-interactive execution.
        """
        logger.info("⚡ Worker executing via CLI: %s...", objective[:50])
        
        command = [
            "gemini",
            "-m", self.model,
            "--yolo",
            str(objective)
        ]

        try:
            # We run blocking subprocess in an executor to avoid halting the async loop
            loop = asyncio.get_running_loop()
            result = await loop.run_in_executor(
                None,
                self._run_subprocess,
                command,
                cwd
            )
            return result
        except Exception as exc:
            logger.error("CLI Worker failed to spawn: %s", exc)
            return {"status": "error", "output": str(exc), "diff": ""}

    def _run_subprocess(self, command: list[str], cwd: str) -> dict:
        """Runs the actual blocking subprocess."""
        try:
            # Execute Gemini CLI
            process = subprocess.run(
                command,
                cwd=cwd,
                capture_output=True,
                text=True,
                # Increase timeout since Gemini can take 60+ seconds for large codebase changes
                timeout=180
            )

            cli_output = process.stdout + "\n" + process.stderr

            if process.returncode != 0:
                logger.warning("CLI Worker returned non-zero code: %d", process.returncode)
                logger.debug("CLI Stderr: %s", process.stderr)

            # Capture Git Diff as context for the Local Manager
            diff_process = subprocess.run(
                ["git", "diff"],
                cwd=cwd,
                capture_output=True,
                text=True,
                timeout=10
            )
            # Strict Token Truncator: Limit heavily to avoid Local LLM Context Collapse
            raw_diff = diff_process.stdout if diff_process.returncode == 0 else "Git diff failed or unsupported."
            git_diff = raw_diff.strip()
            if len(git_diff) > 1000:
                git_diff = git_diff[:1000] + "\n... [DIFF TRUNCATED TO PROTECT CONTEXT WINDOW] ..."

            return {
                "status": "success" if process.returncode == 0 else "failed",
                "output": cli_output.strip()[:2000], # Also limit CLI output
                "diff": git_diff
            }

        except subprocess.TimeoutExpired:
            return {"status": "timeout", "output": "The Gemini CLI process timed out after 180 seconds.", "diff": ""}
        except FileNotFoundError:
            return {"status": "error", "output": "gemini cli not found. Ensure it is installed globally via npm.", "diff": ""}
        except Exception as exc:
            return {"status": "error", "output": str(exc), "diff": ""}
