"""
command_resolver.py — Command Map Authority for the Supervisor.

Loads the complete list of 2,483+ valid VS Code / Antigravity command IDs
from ag-commands.txt (generated by the .ag-tools/cmd-dump extension) and
provides:

  • is_valid_command(cmd_id)  — O(1) exact-match check
  • resolve_command(intent, default_label) — fuzzy match + cache
  • find_command(query) — substring search for debugging
  • suggest_commands(query, n) — top-N fuzzy suggestions

All functions are safe to call even if ag-commands.txt is missing — they
gracefully fall back to empty results so existing supervisor behaviour is
never broken.
"""

import difflib
import logging
from pathlib import Path
from typing import Optional

from . import config

logger = logging.getLogger("supervisor.command_resolver")

# ─────────────────────────────────────────────────────────────
# Command Map Loading
# ─────────────────────────────────────────────────────────────

_COMMANDS: frozenset[str] = frozenset()
_COMMANDS_LIST: list[str] = []  # Sorted list for difflib


def _load_commands() -> tuple[frozenset[str], list[str]]:
    """
    Load command IDs from ag-commands.txt.

    Skips comment lines (starting with #) and blank lines.
    Returns (frozenset for O(1) lookups, sorted list for fuzzy matching).
    """
    ag_path = config.AG_COMMANDS_PATH
    if not ag_path.exists():
        logger.warning(
            "ag-commands.txt not found at %s — command resolver disabled. "
            "Run the .ag-tools/cmd-dump extension to generate it.",
            ag_path,
        )
        return frozenset(), []

    try:
        raw = ag_path.read_text(encoding="utf-8")
        commands = []
        for line in raw.splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                commands.append(line)

        cmd_set = frozenset(commands)
        cmd_list = sorted(commands)
        logger.info(
            "✅ Loaded %d command IDs from ag-commands.txt", len(cmd_set)
        )
        return cmd_set, cmd_list

    except Exception as exc:
        logger.warning("Failed to load ag-commands.txt: %s", exc)
        return frozenset(), []


def reload_commands() -> int:
    """Force-reload the command map. Returns the number of commands loaded."""
    global _COMMANDS, _COMMANDS_LIST
    _COMMANDS, _COMMANDS_LIST = _load_commands()
    return len(_COMMANDS)


# Load on import
_COMMANDS, _COMMANDS_LIST = _load_commands()


# ─────────────────────────────────────────────────────────────
# Known Intent → Command ID Mapping
# ─────────────────────────────────────────────────────────────
# These are verified mappings from supervisor intent keys to
# actual command IDs discovered in ag-commands.txt.

INTENT_TO_COMMAND_ID: dict[str, str] = {
    # Agent / Chat
    "open_agent_chat": "Open Chat with Agent",
    "start_new_conversation": "antigravity.startNewConversation",
    "toggle_chat_focus": "antigravity.toggleChatFocus",
    "open_conversation_picker": "antigravity.openConversationPicker",
    "agent_panel_focus": "antigravity.agentPanel.focus",
    "agent_panel_open": "antigravity.agentPanel.open",
    "agent_side_panel_focus": "antigravity.agentSidePanel.focus",
    "initialize_agent": "antigravity.initializeAgent",
    "switch_workspace_agent": "antigravity.switchBetweenWorkspaceAndAgent",

    # Terminal
    "create_terminal": "workbench.action.terminal.new",
    "create_new_terminal": "workbench.action.terminal.new",
    "toggle_terminal": "workbench.action.terminal.toggleTerminal",
    "focus_terminal": "workbench.action.terminal.focus",
    "kill_terminal": "workbench.action.terminal.kill",
    "split_terminal": "workbench.action.terminal.split",
    "clear_terminal": "workbench.action.terminal.clear",

    # Extension Host
    "restart_extension_host": "workbench.action.restartExtensionHost",
    "developer_restart_extension_host": "workbench.action.restartExtensionHost",

    # Window / Layout
    "reload_window": "workbench.action.reloadWindow",
    "toggle_sidebar": "workbench.action.toggleSidebarVisibility",
    "toggle_panel": "workbench.action.togglePanel",
    "toggle_fullscreen": "workbench.action.toggleFullScreen",
    "toggle_dev_tools": "workbench.action.toggleDevTools",
    "open_settings": "workbench.action.openSettings",
    "open_keybindings": "workbench.action.openGlobalKeybindings",
    "show_commands": "workbench.action.showCommands",
    "focus_editor": "workbench.action.focusActiveEditorGroup",
    "close_editor": "workbench.action.closeActiveEditor",

    # Files
    "new_file": "workbench.action.files.newFile",
    "save_file": "workbench.action.files.save",
    "save_all": "workbench.action.files.saveAll",
    "open_file": "workbench.action.files.openFile",
    "open_folder": "workbench.action.files.openFolder",
    "find_in_files": "workbench.action.findInFiles",
    "replace_in_files": "workbench.action.replaceInFiles",

    # Editor
    "format_document": "editor.action.formatDocument",
    "go_to_definition": "editor.action.revealDefinition",
    "find_references": "editor.action.findReferences",
    "rename_symbol": "editor.action.rename",
    "quick_fix": "editor.action.quickFix",

    # Debug
    "start_debugging": "workbench.action.debug.start",
    "stop_debugging": "workbench.action.debug.stop",
    "continue_debugging": "workbench.action.debug.continue",
    "step_over": "workbench.action.debug.stepOver",

    # Git / SCM
    "git_push": "workbench.scm.focus",  # No direct "git push" command — SCM view

    # Output / Problems
    "show_output": "workbench.action.output.toggleOutput",
    "show_problems": "workbench.actions.view.problems",
    "focus_problems": "workbench.action.problems.focus",

    # Extensions
    "install_extensions": "workbench.extensions.action.installExtensions",
    "focus_extensions": "workbench.extensions.action.focusExtensionsView",

    # Antigravity specific
    "open_review_changes": "antigravity.openReviewChanges",
    "open_troubleshooting": "antigravity.openTroubleshooting",
    "open_docs": "antigravity.openDocs",
    "open_issue_reporter": "antigravity.openIssueReporter",
    "reload_antigravity_window": "antigravity.reloadWindow",
    "open_quick_settings": "antigravity.openQuickSettingsPanel",
    "download_diagnostics": "antigravity.downloadDiagnostics",
    "toggle_manager_devtools": "antigravity.toggleManagerDevTools",
    "accept_agent_step": "antigravity.agent.acceptAgentStep",
    "reject_agent_step": "antigravity.agent.rejectAgentStep",
}


# ─────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────

def is_valid_command(cmd_id: str) -> bool:
    """Check if a command ID exists in the environment (O(1))."""
    return cmd_id in _COMMANDS


def resolve_command(intent_key: str, default_label: str) -> tuple[str, str]:
    """
    Resolve an intent to the best command string for the palette.

    Returns: (command_to_type, source)
      - source is one of: "intent_map", "exact_match", "fuzzy", "default"

    Priority:
      1. Known intent → command ID mapping (INTENT_TO_COMMAND_ID)
      2. Exact match of default_label in _COMMANDS
      3. Fuzzy match against _COMMANDS_LIST
      4. Fall back to default_label (existing behaviour)
    """
    # 1. Check intent map
    if intent_key in INTENT_TO_COMMAND_ID:
        cmd_id = INTENT_TO_COMMAND_ID[intent_key]
        if is_valid_command(cmd_id):
            logger.info(
                "🗺️  Intent '%s' → '%s' (from intent map)", intent_key, cmd_id
            )
            return cmd_id, "intent_map"
        else:
            logger.warning(
                "🗺️  Intent map has '%s' → '%s' but command not in ag-commands.txt!",
                intent_key, cmd_id,
            )

    # 2. Check if default_label is itself a valid command ID
    if is_valid_command(default_label):
        logger.info(
            "🗺️  Default label '%s' is a valid command ID", default_label
        )
        return default_label, "exact_match"

    # 3. Fuzzy match (only if we have commands loaded)
    if _COMMANDS_LIST:
        # Normalize: convert human-readable to potential command ID patterns
        # e.g. "Open Chat with Agent" → try matching "antigravity.openAgent" etc.
        intent_words = intent_key.replace("_", ".").lower()

        matches = difflib.get_close_matches(
            intent_words, _COMMANDS_LIST, n=3, cutoff=0.5
        )
        if matches:
            best = matches[0]
            logger.info(
                "🗺️  Fuzzy matched '%s' → '%s' (from %d candidates)",
                intent_key, best, len(matches),
            )
            return best, "fuzzy"

        # Also try matching the default label directly
        label_lower = default_label.lower().replace(" ", ".").replace(":", "")
        matches2 = difflib.get_close_matches(
            label_lower, _COMMANDS_LIST, n=3, cutoff=0.4
        )
        if matches2:
            best = matches2[0]
            logger.info(
                "🗺️  Fuzzy matched label '%s' → '%s'", default_label, best
            )
            return best, "fuzzy"

    # 4. Fallback: return the original default label
    logger.info(
        "🗺️  No command map match for '%s' — using default: '%s'",
        intent_key, default_label,
    )
    return default_label, "default"


def find_command(query: str) -> list[str]:
    """
    Search for command IDs containing the query string (case-insensitive).
    Useful for debugging and exploration.

    Returns up to 20 matches.
    """
    query_lower = query.lower()
    results = [cmd for cmd in _COMMANDS_LIST if query_lower in cmd.lower()]
    return results[:20]


def suggest_commands(query: str, n: int = 5) -> list[str]:
    """
    Get the top-N fuzzy suggestions for a query.
    Uses difflib.get_close_matches for fuzzy matching.
    """
    if not _COMMANDS_LIST:
        return []
    return difflib.get_close_matches(query, _COMMANDS_LIST, n=n, cutoff=0.3)


def validate_and_warn(action: str) -> Optional[str]:
    """
    Validate a command palette action string.

    If it looks like a programmatic command ID (e.g. "workbench.action.xxx")
    but doesn't exist in ag-commands.txt, log a warning and return suggestions.

    If it looks like a human-readable label (contains spaces, colons), skip
    validation since those are matched by the palette's fuzzy search.

    Returns None if valid/skipped, or a warning string with suggestions.
    """
    # Human-readable labels (e.g. "Terminal: Create New Terminal") are fine
    if " " in action or ":" in action:
        return None

    # Looks like a programmatic command ID
    if is_valid_command(action):
        return None

    # Not found — suggest alternatives
    suggestions = suggest_commands(action, n=3)
    if suggestions:
        msg = (
            f"Command '{action}' not found in ag-commands.txt. "
            f"Did you mean: {', '.join(suggestions)}?"
        )
    else:
        msg = f"Command '{action}' not found in ag-commands.txt and no close matches found."

    logger.warning("🗺️  %s", msg)
    return msg


def get_stats() -> dict:
    """Return stats about the loaded command map."""
    return {
        "total_commands": len(_COMMANDS),
        "intent_mappings": len(INTENT_TO_COMMAND_ID),
        "ag_commands_path": str(config.AG_COMMANDS_PATH),
        "loaded": len(_COMMANDS) > 0,
    }
