"""
finops_engine.py — V28 Autonomous FinOps Engine

Cost-aware optimization engine. Profiles compute costs per transaction,
detects margin decay from recently merged features, and autonomously
generates refactor epics to optimize code for infrastructure profitability.

Pipeline:
  1. Ingest APM metrics (CPU, memory, DB execution times, request counts)
  2. Calculate unit cost per transaction using cloud provider pricing tiers
  3. Compare against baseline — detect margin decay (> 15% cost increase)
  4. Filter: only optimize high-traffic routes (> MIN_TRAFFIC_FOR_FINOPS)
  5. Generate REFACTOR_EPIC.md targeting the expensive route
  6. Temporal Planner optimizes: raw SQL, payload reduction, caching layers

Safety:
  - Traffic threshold: ignores low-traffic endpoints (premature optimization)
  - Caching bounds: blocks caching of real-time financial/checkout data
  - Approved providers: blocks rogue infrastructure migrations
  - Billing purity: evaluates pure compute costs, excludes interest/penalties
"""

import json
import logging
import os
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger("supervisor.finops_engine")

# Cloud provider pricing tiers (cost per unit)
# These are approximate $/GB-hour and $/vCPU-hour rates
_PRICING_TIERS = {
    "vercel": {
        "compute_per_gb_hour": 0.18,
        "memory_per_gb_hour": 0.09,
        "bandwidth_per_gb": 0.15,
        "db_query_per_1000": 0.004,
    },
    "railway": {
        "compute_per_gb_hour": 0.20,
        "memory_per_gb_hour": 0.10,
        "bandwidth_per_gb": 0.10,
        "db_query_per_1000": 0.005,
    },
    "aws": {
        "compute_per_gb_hour": 0.085,
        "memory_per_gb_hour": 0.047,
        "bandwidth_per_gb": 0.09,
        "db_query_per_1000": 0.003,
    },
}

# Data that must NEVER be cached
_NO_CACHE_PATTERNS = [
    "checkout", "payment", "transaction", "balance",
    "cart_total", "order_total", "invoice", "billing",
    "real_time", "realtime", "live_price", "exchange_rate",
]

# Billing items to exclude from cost calculations (Shariah compliance)
_EXCLUDED_BILLING_ITEMS = [
    "interest", "late_fee", "penalty", "credit_scheme",
    "financing_charge", "apr", "usury",
]


class FinOpsEngine:
    """
    Autonomous FinOps engine. Profiles compute costs, detects margin decay,
    and generates refactor epics.
    """

    REFACTOR_PROMPT = (
        "You are a senior performance engineer. Analyze this APM report showing "
        "an expensive API route. Propose a minimal refactoring plan.\n\n"
        "OPTIMIZATION STRATEGIES (in order of preference):\n"
        "1. Replace ORM queries with optimized raw SQL.\n"
        "2. Add database indexes for slow queries.\n"
        "3. Reduce response payload size (remove unused fields).\n"
        "4. Add caching layer (Redis/in-memory) for read-heavy endpoints.\n"
        "5. Batch multiple DB queries into single queries.\n"
        "6. Add pagination to unbounded list endpoints.\n\n"
        "STRICT RULES:\n"
        "- Do NOT cache real-time financial data (checkout totals, live prices).\n"
        "- Do NOT suggest infrastructure migrations.\n"
        "- Do NOT add interest-bearing or credit-based cost optimizations.\n"
        "- Focus on PURE compute cost reduction.\n\n"
        "Output strict JSON:\n"
        '{"route": "/api/products", "strategy": "raw_sql", '
        '"description": "...", "estimated_savings_pct": 40, '
        '"files_to_modify": ["src/api/products.js"]}'
    )

    REFACTOR_EPIC_TEMPLATE = """# REFACTOR EPIC — Auto-generated by FinOps Engine

## Cost Alert
Route `{route}` has exceeded the margin decay threshold.

## Current Metrics
- Avg response time: {avg_response_ms}ms
- Memory per request: {memory_per_request_mb}MB
- Daily requests: {daily_requests}
- Current unit cost: ${current_unit_cost:.6f}/req
- Baseline unit cost: ${baseline_unit_cost:.6f}/req
- Cost increase: {cost_increase_pct:.1f}%
- Projected monthly cost increase: ${monthly_increase:.2f}

## Optimization Strategy
{strategy}: {description}

## Files to Modify
{files_list}

## Constraints
- This is a PERFORMANCE REFACTOR. Minimize functional changes.
- Do NOT cache: {no_cache_list}
- Do NOT migrate infrastructure providers.
- Do NOT introduce interest-bearing cost optimizations.
- Write a performance regression test.
- Verify unit cost drops below baseline after changes.
"""

    def __init__(self, workspace_path: str = "."):
        self._workspace = Path(workspace_path)
        self._baselines_dir = self._workspace / ".ag-memory" / "finops"
        self._baselines_dir.mkdir(parents=True, exist_ok=True)
        self._provider = os.getenv("DEPLOY_PROVIDER", "vercel").lower()
        self._pricing = _PRICING_TIERS.get(self._provider, _PRICING_TIERS["vercel"])

    # ────────────────────────────────────────────────
    # APM Ingestion
    # ────────────────────────────────────────────────

    def ingest_apm_report(self, report: Dict) -> Tuple[bool, List[Dict]]:
        """
        Parse an APM report and identify expensive routes.

        Expected format:
        {
            "period": "2026-02-20",
            "routes": [
                {
                    "route": "/api/products",
                    "method": "GET",
                    "avg_response_ms": 340,
                    "p99_response_ms": 1200,
                    "memory_per_request_mb": 45,
                    "cpu_time_ms": 120,
                    "db_queries": 12,
                    "avg_payload_kb": 85,
                    "daily_requests": 15000,
                    "error_rate": 0.02
                },
                ...
            ]
        }

        Returns (has_expensive_routes, flagged_routes_with_costs).
        """
        from . import config

        routes = report.get("routes", [])
        if not routes:
            return False, []

        flagged = []
        for route_data in routes:
            daily_requests = route_data.get("daily_requests", 0)
            route_path = route_data.get("route", "")

            # Skip low-traffic routes (premature optimization guard)
            if daily_requests < config.MIN_TRAFFIC_FOR_FINOPS:
                continue

            # Calculate unit cost
            unit_cost = self.calculate_unit_cost(route_data)
            route_data["unit_cost"] = unit_cost

            # Check against baseline
            baseline = self._get_baseline(route_path)
            if baseline is not None:
                increase = (unit_cost - baseline) / baseline if baseline > 0 else 0
                route_data["baseline_unit_cost"] = baseline
                route_data["cost_increase_pct"] = increase * 100

                if increase > config.MARGIN_DECAY_THRESHOLD:
                    route_data["monthly_increase"] = (
                        (unit_cost - baseline) * daily_requests * 30
                    )
                    flagged.append(route_data)
            else:
                # No baseline exists — save current as baseline
                self._save_baseline(route_path, unit_cost)

        if flagged:
            flagged.sort(key=lambda r: r.get("monthly_increase", 0), reverse=True)
            logger.info("💰 %d expensive routes flagged for refactoring.", len(flagged))

        return bool(flagged), flagged

    def calculate_unit_cost(self, route_data: Dict) -> float:
        """
        Calculate the cost per transaction for a route.
        Uses pure compute costs only — excludes interest/penalties.

        Cost = CPU time cost + memory cost + DB query cost + bandwidth cost
        """
        # CPU cost: convert ms to hours, apply pricing
        cpu_ms = route_data.get("cpu_time_ms", 0)
        cpu_hours = cpu_ms / 3_600_000
        cpu_cost = cpu_hours * self._pricing["compute_per_gb_hour"]

        # Memory cost: convert MB to GB, assume held for request duration
        memory_mb = route_data.get("memory_per_request_mb", 0)
        memory_gb = memory_mb / 1024
        avg_response_s = route_data.get("avg_response_ms", 0) / 1000
        memory_hours = memory_gb * (avg_response_s / 3600)
        memory_cost = memory_hours * self._pricing["memory_per_gb_hour"]

        # DB query cost
        db_queries = route_data.get("db_queries", 0)
        db_cost = (db_queries / 1000) * self._pricing["db_query_per_1000"]

        # Bandwidth cost
        payload_kb = route_data.get("avg_payload_kb", 0)
        payload_gb = payload_kb / (1024 * 1024)
        bandwidth_cost = payload_gb * self._pricing["bandwidth_per_gb"]

        total = cpu_cost + memory_cost + db_cost + bandwidth_cost

        # Filter out any excluded billing items from input data
        for key in route_data:
            if any(excl in key.lower() for excl in _EXCLUDED_BILLING_ITEMS):
                logger.debug("Excluding billing item from cost calc: %s", key)

        return total

    # ────────────────────────────────────────────────
    # Baseline Management
    # ────────────────────────────────────────────────

    def _get_baseline(self, route: str) -> Optional[float]:
        """Get the baseline unit cost for a route."""
        safe_name = route.replace("/", "_").strip("_") + ".json"
        path = self._baselines_dir / safe_name
        if path.exists():
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
                return data.get("unit_cost")
            except Exception:
                return None
        return None

    def _save_baseline(self, route: str, unit_cost: float):
        """Save the baseline unit cost for a route."""
        safe_name = route.replace("/", "_").strip("_") + ".json"
        path = self._baselines_dir / safe_name
        data = {"route": route, "unit_cost": unit_cost, "saved_at": time.time()}
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")

    def reset_baseline(self, route: str, new_cost: float):
        """Reset a route's baseline after successful optimization."""
        self._save_baseline(route, new_cost)
        logger.info("📊 Baseline reset for %s: $%.6f/req", route, new_cost)

    # ────────────────────────────────────────────────
    # Caching Safety Bounds
    # ────────────────────────────────────────────────

    @staticmethod
    def is_cacheable(route: str, context: str = "") -> bool:
        """
        Check if a route's data is safe to cache.
        Blocks caching of real-time financial/checkout data.
        """
        combined = f"{route} {context}".lower()
        for pattern in _NO_CACHE_PATTERNS:
            if pattern in combined:
                logger.debug("Cache blocked for %s (matched: %s)", route, pattern)
                return False
        return True

    # ────────────────────────────────────────────────
    # Provider Lockdown
    # ────────────────────────────────────────────────

    @staticmethod
    def validate_provider(provider: str) -> Tuple[bool, str]:
        """Ensure the provider is in the approved list."""
        from . import config
        if provider.lower() in config.APPROVED_DEPLOY_PROVIDERS:
            return True, f"Provider {provider} is approved."
        return False, (
            f"Provider '{provider}' is NOT approved. "
            f"Approved providers: {config.APPROVED_DEPLOY_PROVIDERS}. "
            "Infrastructure migrations are blocked."
        )

    # ────────────────────────────────────────────────
    # REFACTOR_EPIC.md Generation
    # ────────────────────────────────────────────────

    def generate_refactor_epic(self, route_data: Dict, strategy: Dict = None) -> Tuple[bool, str]:
        """Generate a REFACTOR_EPIC.md for an expensive route."""
        route = route_data.get("route", "/unknown")
        files = strategy.get("files_to_modify", []) if strategy else []
        files_list = "\n".join(f"- `{f}`" for f in files) if files else "- To be identified"

        no_cache = [p for p in _NO_CACHE_PATTERNS if p in route.lower()]
        no_cache_list = ", ".join(no_cache) if no_cache else "checkout, payment, real-time data"

        epic_content = self.REFACTOR_EPIC_TEMPLATE.format(
            route=route,
            avg_response_ms=route_data.get("avg_response_ms", 0),
            memory_per_request_mb=route_data.get("memory_per_request_mb", 0),
            daily_requests=route_data.get("daily_requests", 0),
            current_unit_cost=route_data.get("unit_cost", 0),
            baseline_unit_cost=route_data.get("baseline_unit_cost", 0),
            cost_increase_pct=route_data.get("cost_increase_pct", 0),
            monthly_increase=route_data.get("monthly_increase", 0),
            strategy=strategy.get("strategy", "optimize") if strategy else "optimize",
            description=strategy.get("description", "Reduce compute overhead") if strategy else "Identify and reduce compute overhead",
            files_list=files_list,
            no_cache_list=no_cache_list,
        )

        epic_path = self._workspace / "REFACTOR_EPIC.md"
        try:
            epic_path.write_text(epic_content, encoding="utf-8")
            logger.info("💰 Generated REFACTOR_EPIC.md for %s", route)
            return True, str(epic_path)
        except Exception as exc:
            return False, f"Failed to write refactor epic: {exc}"

    # ────────────────────────────────────────────────
    # LLM Optimization Strategy
    # ────────────────────────────────────────────────

    async def get_optimization_strategy(
        self,
        route_data: Dict,
        local_manager=None,
    ) -> Tuple[bool, Dict]:
        """Route expensive APM data to the LLM for optimization strategy."""
        manager = local_manager
        if not manager:
            return False, {"error": "No Local Manager available."}

        import re as _re
        user_prompt = (
            f"EXPENSIVE ROUTE:\n{json.dumps(route_data, indent=2)}\n\n"
            f"Cacheable: {self.is_cacheable(route_data.get('route', ''))}\n"
            "Propose an optimization strategy."
        )

        try:
            raw = await manager.ask_local_model(
                system_prompt=self.REFACTOR_PROMPT,
                user_prompt=user_prompt,
                temperature=0.0,
            )
            if not raw:
                return False, {"error": "LLM returned empty."}

            json_match = _re.search(r'\{[^}]+\}', raw, _re.DOTALL)
            if json_match:
                return True, json.loads(json_match.group())
            return False, {"error": f"Could not parse: {raw[:200]}"}
        except Exception as exc:
            return False, {"error": f"Strategy generation failed: {exc}"}

    # ────────────────────────────────────────────────
    # Full FinOps Pipeline
    # ────────────────────────────────────────────────

    async def process_apm_report(
        self,
        report: Dict,
        local_manager=None,
    ) -> Tuple[bool, str]:
        """
        Complete FinOps pipeline:
        1. Ingest APM report
        2. Flag expensive routes
        3. Get optimization strategy
        4. Generate REFACTOR_EPIC.md
        """
        has_issues, flagged = self.ingest_apm_report(report)
        if not has_issues:
            return False, "No margin decay detected."

        # Take the worst offender
        worst = flagged[0]
        route = worst.get("route", "")

        # Get LLM strategy
        strategy = None
        if local_manager:
            strat_ok, strat_data = await self.get_optimization_strategy(worst, local_manager)
            if strat_ok:
                strategy = strat_data

        # Generate epic
        epic_ok, epic_path = self.generate_refactor_epic(worst, strategy)
        if not epic_ok:
            return False, epic_path

        return True, epic_path

    def get_cost_summary(self, report: Dict) -> Dict:
        """Generate a cost summary for all routes in a report."""
        routes = report.get("routes", [])
        summary = {
            "total_daily_cost": 0,
            "total_monthly_cost": 0,
            "route_costs": [],
            "provider": self._provider,
        }

        for route_data in routes:
            unit_cost = self.calculate_unit_cost(route_data)
            daily_reqs = route_data.get("daily_requests", 0)
            daily_cost = unit_cost * daily_reqs
            summary["total_daily_cost"] += daily_cost
            summary["route_costs"].append({
                "route": route_data.get("route", ""),
                "unit_cost": unit_cost,
                "daily_cost": daily_cost,
                "monthly_cost": daily_cost * 30,
            })

        summary["total_monthly_cost"] = summary["total_daily_cost"] * 30
        summary["route_costs"].sort(key=lambda r: r["daily_cost"], reverse=True)
        return summary
