"""
growth_engine.py — V27 Autonomous Growth Engine

Proactive growth mechanism. Instead of only reacting to crashes, this engine
ingests quantitative user analytics, identifies underperforming UI components,
generates experiment hypotheses, deploys A/B tests behind feature flags,
evaluates results with statistical rigor, and auto-merges winners while
deleting losing code and stale toggles.

Pipeline:
  1. Ingest daily conversion report (PostHog/Mixpanel webhook or JSON)
  2. Detect underperforming components (below threshold conversion rate)
  3. Generate hypothesis via LLM → write EXPERIMENT_EPIC.md
  4. Temporal Planner wraps variant in feature flag
  5. Deployment Engine ships dual state to production
  6. After 48h, evaluate: minimum sample + statistical significance
  7. Winner merged permanently, loser code + flag deleted

Safety:
  - MIN_SAMPLE_SIZE = 100 per variant (prevents false positives from noise)
  - Scope restricted to frontend/UI directories only
  - No experiments on migrations, payments, or backend APIs
"""

import hashlib
import json
import logging
import math
import os
import re
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger("supervisor.growth_engine")

MIN_SAMPLE_SIZE = 100
EXPERIMENT_DURATION_H = 48
SIGNIFICANCE_THRESHOLD = 0.05  # p < 0.05

# Directories where experiments are allowed
_ALLOWED_SCOPES = [
    "src/components", "src/pages", "src/views", "src/layouts",
    "components/", "pages/", "views/", "layouts/", "templates/",
    "app/", "frontend/", "public/", "static/",
]

# Directories where experiments are BLOCKED
_BLOCKED_SCOPES = [
    "migration", "prisma", "alembic", "knex",
    "payments", "billing", "stripe", "checkout/api",
    "api/", "server/", "backend/", "db/", "database/",
]


class GrowthEngine:
    """
    Autonomous growth engine. Ingests analytics, generates hypotheses,
    deploys A/B experiments, evaluates, and cleans up.
    """

    HYPOTHESIS_PROMPT = (
        "You are a senior growth engineer and UX strategist. Analyze this "
        "analytics report showing underperforming UI components.\n\n"
        "RULES:\n"
        "1. Identify the component with the worst conversion rate.\n"
        "2. Propose ONE specific, actionable hypothesis to improve it.\n"
        "3. The change must be implementable in 1-3 files.\n"
        "4. The change must be wrappable in a feature flag.\n"
        "5. Do NOT propose backend or API changes.\n\n"
        "Output strict JSON:\n"
        '{"component": "CheckoutButton", "file": "src/components/CheckoutButton.jsx", '
        '"current_conversion": 2.1, "hypothesis": "Move CTA above the fold and increase '
        'contrast", "variant_description": "...", "flag_name": "exp_checkout_cta_v2"}'
    )

    EXPERIMENT_EPIC_TEMPLATE = """# EXPERIMENT EPIC — Auto-generated by Growth Engine

## Hypothesis
{hypothesis}

## Target Component
`{component}` in `{file}`

## Current Conversion Rate
{current_conversion}%

## Variant Description
{variant_description}

## Feature Flag
`{flag_name}`

## Implementation Requirements
1. Create the variant implementation.
2. Wrap the variant in a feature flag: `{flag_name}`
3. The CONTROL (original) must remain the default when the flag is OFF.
4. The VARIANT must activate when the flag is ON.
5. Both states must render without errors.
6. Add the flag to the project's feature flag configuration.

## Scope Restriction
This experiment is restricted to frontend/UI code ONLY.
Do NOT modify backend, API, database, or payment logic.
"""

    def __init__(self, local_manager=None, workspace_path: str = "."):
        self._manager = local_manager
        self._workspace = Path(workspace_path)
        self._experiments_dir = self._workspace / ".ag-memory" / "experiments"
        self._experiments_dir.mkdir(parents=True, exist_ok=True)

    # ────────────────────────────────────────────────
    # Analytics Ingestion
    # ────────────────────────────────────────────────

    def ingest_report(self, report: Dict) -> Tuple[bool, List[Dict]]:
        """
        Parse a daily conversion report and identify underperformers.

        Expected report format:
        {
            "date": "2026-02-20",
            "components": [
                {
                    "name": "CheckoutButton",
                    "file": "src/components/CheckoutButton.jsx",
                    "impressions": 5200,
                    "conversions": 109,
                    "conversion_rate": 2.1
                },
                ...
            ]
        }

        Returns (has_underperformers, underperforming_components).
        """
        components = report.get("components", [])
        if not components:
            return False, []

        # Calculate mean conversion rate
        rates = [c.get("conversion_rate", 0) for c in components if c.get("impressions", 0) > 0]
        if not rates:
            return False, []

        mean_rate = sum(rates) / len(rates)

        # Flag components significantly below mean (< 50% of mean)
        underperformers = []
        for comp in components:
            rate = comp.get("conversion_rate", 0)
            impressions = comp.get("impressions", 0)
            file_path = comp.get("file", "")

            # Must have meaningful traffic
            if impressions < MIN_SAMPLE_SIZE:
                continue

            # Must be significantly below average
            if rate < mean_rate * 0.5:
                # Scope check: only frontend files
                if self._is_in_scope(file_path):
                    underperformers.append(comp)

        if underperformers:
            # Sort by worst conversion rate
            underperformers.sort(key=lambda c: c.get("conversion_rate", 0))
            logger.info(
                "📉 Found %d underperforming components (mean: %.1f%%)",
                len(underperformers), mean_rate,
            )

        return bool(underperformers), underperformers

    def _is_in_scope(self, file_path: str) -> bool:
        """Check if a file is within allowed experiment scope."""
        lower = file_path.lower().replace("\\", "/")

        # Block restricted directories
        for blocked in _BLOCKED_SCOPES:
            if blocked in lower:
                logger.debug("Blocked scope: %s contains %s", file_path, blocked)
                return False

        # Must be in allowed directories
        for allowed in _ALLOWED_SCOPES:
            if allowed in lower:
                return True

        return False

    # ────────────────────────────────────────────────
    # Hypothesis Generation
    # ────────────────────────────────────────────────

    async def generate_hypothesis(
        self,
        underperformers: List[Dict],
    ) -> Tuple[bool, Dict]:
        """
        Route underperforming components to the LLM for hypothesis generation.
        Returns (success, hypothesis_dict).
        """
        if not self._manager:
            return False, {"error": "No Local Manager available."}

        report_text = json.dumps(underperformers[:3], indent=2)
        user_prompt = (
            f"UNDERPERFORMING COMPONENTS:\n{report_text}\n\n"
            "Generate a growth hypothesis for the worst performer."
        )

        try:
            raw = await self._manager.ask_local_model(
                system_prompt=self.HYPOTHESIS_PROMPT,
                user_prompt=user_prompt,
                temperature=0.3,
            )

            if not raw:
                return False, {"error": "LLM returned empty response."}

            json_match = re.search(r'\{[^}]+\}', raw, re.DOTALL)
            if json_match:
                hypothesis = json.loads(json_match.group())
                return True, hypothesis

            return False, {"error": f"Could not parse hypothesis: {raw[:200]}"}

        except Exception as exc:
            return False, {"error": f"Hypothesis generation failed: {exc}"}

    # ────────────────────────────────────────────────
    # Experiment Epic Generation
    # ────────────────────────────────────────────────

    def generate_experiment_epic(self, hypothesis: Dict) -> Tuple[bool, str]:
        """Write an EXPERIMENT_EPIC.md from the hypothesis."""
        epic_content = self.EXPERIMENT_EPIC_TEMPLATE.format(
            hypothesis=hypothesis.get("hypothesis", "Improve conversion"),
            component=hypothesis.get("component", "Unknown"),
            file=hypothesis.get("file", "unknown"),
            current_conversion=hypothesis.get("current_conversion", 0),
            variant_description=hypothesis.get("variant_description", "Improved variant"),
            flag_name=hypothesis.get("flag_name", "exp_unnamed"),
        )

        epic_path = self._workspace / "EXPERIMENT_EPIC.md"
        try:
            epic_path.write_text(epic_content, encoding="utf-8")
            logger.info("🧪 Generated EXPERIMENT_EPIC.md for %s", hypothesis.get("component"))

            # Save experiment state
            self._save_experiment_state(hypothesis)
            return True, str(epic_path)
        except Exception as exc:
            return False, f"Failed to write experiment epic: {exc}"

    def _save_experiment_state(self, hypothesis: Dict):
        """Save the experiment state for later evaluation."""
        flag_name = hypothesis.get("flag_name", "exp_unnamed")
        state = {
            "flag_name": flag_name,
            "component": hypothesis.get("component", ""),
            "file": hypothesis.get("file", ""),
            "hypothesis": hypothesis.get("hypothesis", ""),
            "baseline_conversion": hypothesis.get("current_conversion", 0),
            "started_at": time.time(),
            "status": "running",  # running | evaluating | concluded
            "result": None,
        }
        state_path = self._experiments_dir / f"{flag_name}.json"
        state_path.write_text(json.dumps(state, indent=2), encoding="utf-8")

    # ────────────────────────────────────────────────
    # A/B Evaluation (after 48h)
    # ────────────────────────────────────────────────

    def evaluate_experiment(
        self,
        flag_name: str,
        results: Dict,
    ) -> Tuple[str, str]:
        """
        Evaluate an experiment's results with statistical rigor.

        Expected results format:
        {
            "control": {"impressions": 2500, "conversions": 53},
            "variant": {"impressions": 2500, "conversions": 89}
        }

        Returns (winner: "control"|"variant"|"inconclusive", report).
        """
        control = results.get("control", {})
        variant = results.get("variant", {})

        c_imp = control.get("impressions", 0)
        c_conv = control.get("conversions", 0)
        v_imp = variant.get("impressions", 0)
        v_conv = variant.get("conversions", 0)

        # Minimum sample check
        if c_imp < MIN_SAMPLE_SIZE or v_imp < MIN_SAMPLE_SIZE:
            return "inconclusive", (
                f"Insufficient sample size. Control: {c_imp}, Variant: {v_imp}. "
                f"Minimum required: {MIN_SAMPLE_SIZE} per variant."
            )

        # Calculate conversion rates
        c_rate = c_conv / c_imp if c_imp > 0 else 0
        v_rate = v_conv / v_imp if v_imp > 0 else 0

        # Z-test for two proportions
        p_value = self._two_proportion_z_test(c_conv, c_imp, v_conv, v_imp)

        report_lines = [
            f"Control: {c_rate:.2%} ({c_conv}/{c_imp})",
            f"Variant: {v_rate:.2%} ({v_conv}/{v_imp})",
            f"Lift: {((v_rate - c_rate) / c_rate * 100) if c_rate > 0 else 0:+.1f}%",
            f"p-value: {p_value:.4f}",
            f"Significant: {'Yes' if p_value < SIGNIFICANCE_THRESHOLD else 'No'}",
        ]
        report = "\n".join(report_lines)

        if p_value >= SIGNIFICANCE_THRESHOLD:
            winner = "inconclusive"
        elif v_rate > c_rate:
            winner = "variant"
        else:
            winner = "control"

        # Update experiment state
        self._update_experiment_state(flag_name, winner, report)

        logger.info("🧪 Experiment %s concluded: %s wins", flag_name, winner)
        return winner, report

    @staticmethod
    def _two_proportion_z_test(
        c_conv: int, c_total: int,
        v_conv: int, v_total: int,
    ) -> float:
        """
        Two-proportion Z-test.
        Returns the p-value (two-tailed).
        """
        if c_total == 0 or v_total == 0:
            return 1.0

        p1 = c_conv / c_total
        p2 = v_conv / v_total
        p_pool = (c_conv + v_conv) / (c_total + v_total)

        if p_pool == 0 or p_pool == 1:
            return 1.0

        se = math.sqrt(p_pool * (1 - p_pool) * (1 / c_total + 1 / v_total))
        if se == 0:
            return 1.0

        z = abs(p1 - p2) / se

        # Approximate p-value from Z using the complementary error function
        p_value = 2.0 * (1.0 - _normal_cdf(z))
        return p_value

    def _update_experiment_state(self, flag_name: str, winner: str, report: str):
        """Update the persisted experiment state."""
        state_path = self._experiments_dir / f"{flag_name}.json"
        if state_path.exists():
            state = json.loads(state_path.read_text(encoding="utf-8"))
        else:
            state = {}
        state["status"] = "concluded"
        state["result"] = winner
        state["report"] = report
        state["concluded_at"] = time.time()
        state_path.write_text(json.dumps(state, indent=2), encoding="utf-8")

    # ────────────────────────────────────────────────
    # Flag Cleanup + Dead Code Deletion
    # ────────────────────────────────────────────────

    def cleanup_experiment(
        self,
        flag_name: str,
        winner: str,
        target_file: str,
    ) -> Tuple[bool, str]:
        """
        After experiment concludes:
        - If variant wins: remove the flag, keep variant code only.
        - If control wins: remove the flag, delete variant code.
        - In either case, delete the feature flag conditional.

        Returns (success, description).
        """
        file_path = self._workspace / target_file
        if not file_path.exists():
            return False, f"Target file not found: {target_file}"

        try:
            content = file_path.read_text(encoding="utf-8")
            original = content

            # Remove feature flag conditionals
            # Pattern 1: JS/React style: if (featureFlags.exp_name) { ... } else { ... }
            js_pattern = (
                rf'if\s*\(\s*(?:featureFlags|flags|features)\s*\.\s*{re.escape(flag_name)}\s*\)'
                rf'\s*\{{([^}}]*)\}}\s*else\s*\{{([^}}]*)\}}'
            )
            match = re.search(js_pattern, content, re.DOTALL)
            if match:
                variant_code = match.group(1).strip()
                control_code = match.group(2).strip()
                keep = variant_code if winner == "variant" else control_code
                content = content[:match.start()] + keep + content[match.end():]

            # Pattern 2: Python style: if feature_flags.get("exp_name"):
            py_pattern = (
                rf'if\s+(?:feature_flags|flags)\.get\(\s*["\']{re.escape(flag_name)}["\']\s*\):'
            )
            # For Python, more complex block handling would need AST — mark for manual review
            if re.search(py_pattern, content):
                content = re.sub(
                    py_pattern,
                    f"# EXPERIMENT {flag_name} concluded — {winner} wins. Clean up manually.",
                    content,
                )

            if content != original:
                file_path.write_text(content, encoding="utf-8")
                logger.info(
                    "🧹 Cleaned up feature flag %s from %s (winner: %s)",
                    flag_name, target_file, winner,
                )
                # Remove experiment state file
                state_path = self._experiments_dir / f"{flag_name}.json"
                if state_path.exists():
                    state_path.unlink()
                return True, f"Flag {flag_name} removed, {winner} code kept in {target_file}."

            return False, f"Could not locate flag pattern for {flag_name} in {target_file}."

        except Exception as exc:
            return False, f"Cleanup failed: {exc}"

    # ────────────────────────────────────────────────
    # Pending Experiment Check
    # ────────────────────────────────────────────────

    def get_pending_evaluations(self) -> List[Dict]:
        """
        Return experiments that have been running for >= 48h
        and are ready for evaluation.
        """
        pending = []
        now = time.time()
        cutoff = EXPERIMENT_DURATION_H * 3600

        for state_file in self._experiments_dir.glob("*.json"):
            try:
                state = json.loads(state_file.read_text(encoding="utf-8"))
                if state.get("status") == "running":
                    elapsed = now - state.get("started_at", now)
                    if elapsed >= cutoff:
                        state["elapsed_hours"] = elapsed / 3600
                        pending.append(state)
            except Exception:
                continue

        return pending

    # ────────────────────────────────────────────────
    # Full Growth Pipeline
    # ────────────────────────────────────────────────

    async def process_report(self, report: Dict) -> Tuple[bool, str]:
        """
        Complete growth pipeline:
        1. Ingest analytics report
        2. Identify underperformers
        3. Generate hypothesis
        4. Write EXPERIMENT_EPIC.md
        """
        # Step 1: Ingest
        has_issues, underperformers = self.ingest_report(report)
        if not has_issues:
            return False, "No underperforming components found."

        # Step 2: Generate hypothesis
        hyp_ok, hypothesis = await self.generate_hypothesis(underperformers)
        if not hyp_ok:
            return False, f"Hypothesis generation failed: {hypothesis.get('error', 'unknown')}"

        # Step 3: Scope check on proposed file
        proposed_file = hypothesis.get("file", "")
        if not self._is_in_scope(proposed_file):
            return False, f"Proposed file {proposed_file} is outside experiment scope."

        # Step 4: Generate experiment epic
        epic_ok, epic_path = self.generate_experiment_epic(hypothesis)
        if not epic_ok:
            return False, epic_path

        return True, epic_path


# ─────────────────────────────────────────────────────────────
# Statistical Helpers
# ─────────────────────────────────────────────────────────────

def _normal_cdf(x: float) -> float:
    """
    Approximate the cumulative distribution function of the standard
    normal distribution using the Abramowitz & Stegun approximation.
    """
    a1 = 0.254829592
    a2 = -0.284496736
    a3 = 1.421413741
    a4 = -1.453152027
    a5 = 1.061405429
    p = 0.3275911

    sign = 1 if x >= 0 else -1
    x = abs(x) / math.sqrt(2)

    t = 1.0 / (1.0 + p * x)
    y = 1.0 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * math.exp(-x * x)

    return 0.5 * (1.0 + sign * y)
