"""
telemetry_ingester.py — V26 Production Telemetry Engine (Ouroboros Loop)

Monitors live deployments, catches unhandled exceptions, and autonomously
generates hotfix Epics. The self-healing loop:

  1. Ingest production errors (webhook JSON or Vercel/Sentry log polling)
  2. Filter noise (ignore 404s, client timeouts, minor warnings)
  3. Deduplicate by error signature hash
  4. Rate limit: max 2 autonomous hotfix attempts per unique error per 24h
  5. Root cause analysis via Local Manager
  6. Generate HOTFIX_EPIC.md targeting the exact bug
  7. Stash dirty local state, checkout release SHA
  8. Trigger Temporal Planner → TDD → Deploy pipeline
  9. If 3rd attempt on same error → halt and page the operator

Safety:
  - Error signature hashing prevents infinite hotfix spirals
  - 2-per-24h cap per unique error prevents API/budget burn
  - Release SHA checkout ensures hotfix targets deployed code, not local WIP
"""

import asyncio
import hashlib
import json
import logging
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger("supervisor.telemetry_ingester")

MAX_HOTFIX_ATTEMPTS = 2
RATE_LIMIT_WINDOW_S = 86400  # 24 hours
POLL_INTERVAL_S = 60

# Noise patterns to aggressively filter out
_NOISE_PATTERNS = [
    r"404\s+not\s+found",
    r"net::ERR_",
    r"ECONNRESET",
    r"ECONNREFUSED",
    r"ETIMEDOUT",
    r"client[\s_]?timeout",
    r"favicon\.ico",
    r"robots\.txt",
    r"\bDeprecationWarning\b",
    r"\bExperimentalWarning\b",
    r"ResizeObserver loop",
    r"Loading chunk \d+ failed",
]

# Fatal patterns that indicate real production issues
_FATAL_PATTERNS = [
    r"(?:Unhandled|Uncaught)\s+(?:Exception|Error|Rejection)",
    r"TypeError:\s+\w+\s+is\s+(?:not\s+a\s+function|undefined|null)",
    r"ReferenceError:",
    r"FATAL\s+ERROR",
    r"Internal\s+Server\s+Error",
    r"status[\s:=]+5\d\d",
    r"Process\s+exited\s+with\s+status\s+1",
    r"Segmentation\s+fault",
    r"OOMKilled",
    r"SIGKILL",
    r"panic:",
    r"Traceback \(most recent call last\)",
]


class TelemetryIngester:
    """
    Ingests production errors, deduplicates, rate-limits, and generates
    hotfix Epics for autonomous self-healing.
    """

    ROOT_CAUSE_PROMPT = (
        "You are a senior production incident responder. Analyze this production "
        "stack trace and identify the root cause.\n\n"
        "RULES:\n"
        "1. Identify the EXACT file and line number causing the crash.\n"
        "2. Explain the bug in one sentence.\n"
        "3. Propose a minimal fix (fewest lines changed).\n"
        "4. Do NOT propose refactors — this is a hotfix.\n\n"
        "Output strict JSON:\n"
        '{"file": "path/to/file.py", "line": 42, "root_cause": "...", '
        '"fix_description": "...", "severity": "critical|high|medium"}'
    )

    HOTFIX_EPIC_TEMPLATE = """# HOTFIX EPIC — Auto-generated by Production Telemetry Engine

## Error Signature
`{signature}`

## Root Cause
{root_cause}

## Affected File
`{file}` (line {line})

## Fix Description
{fix_description}

## Constraints
- This is a HOTFIX. Minimal changes only.
- Target the exact release SHA: `{release_sha}`
- Do NOT refactor surrounding code.
- Write a regression test for this specific bug.
- Deploy immediately after tests pass.
"""

    def __init__(self, local_manager=None, workspace_path: str = "."):
        self._manager = local_manager
        self._workspace = Path(workspace_path)
        self._hotfix_dir = self._workspace / ".ag-supervisor"
        self._hotfix_dir.mkdir(parents=True, exist_ok=True)

        # Error tracking: {signature_hash: [(timestamp, attempt_num), ...]}
        self._error_ledger: Dict[str, List[Tuple[float, int]]] = {}
        self._load_ledger()

    # ────────────────────────────────────────────────
    # Noise Filtering
    # ────────────────────────────────────────────────

    @staticmethod
    def is_noise(error_text: str) -> bool:
        """Return True if the error is non-fatal noise to be ignored."""
        lower = error_text.lower()
        for pattern in _NOISE_PATTERNS:
            if re.search(pattern, error_text, re.IGNORECASE):
                return True
        return False

    @staticmethod
    def is_fatal(error_text: str) -> bool:
        """Return True if the error is a genuine fatal production issue."""
        for pattern in _FATAL_PATTERNS:
            if re.search(pattern, error_text, re.IGNORECASE):
                return True
        return False

    # ────────────────────────────────────────────────
    # Error Signature Hashing + Rate Limiting
    # ────────────────────────────────────────────────

    @staticmethod
    def compute_signature(error_text: str) -> str:
        """
        Hash the error into a stable signature.
        Strips timestamps, PIDs, and memory addresses for deduplication.
        """
        # Normalize: strip timestamps, PIDs, hex addresses
        cleaned = re.sub(r'\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}', '', error_text)
        cleaned = re.sub(r'0x[0-9a-fA-F]+', '0xADDR', cleaned)
        cleaned = re.sub(r'pid[:\s]+\d+', 'pid:PID', cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r'\d{10,}', 'TIMESTAMP', cleaned)
        cleaned = re.sub(r'\s+', ' ', cleaned).strip()

        return hashlib.sha256(cleaned.encode()).hexdigest()[:16]

    def check_rate_limit(self, signature: str) -> Tuple[bool, int]:
        """
        Check if this error signature has exceeded the hotfix attempt limit.
        Returns (allowed, attempt_number).
        """
        now = time.time()
        cutoff = now - RATE_LIMIT_WINDOW_S

        # Clean old entries
        if signature in self._error_ledger:
            self._error_ledger[signature] = [
                (ts, num) for ts, num in self._error_ledger[signature]
                if ts > cutoff
            ]

        recent = self._error_ledger.get(signature, [])
        attempt_count = len(recent)

        if attempt_count >= MAX_HOTFIX_ATTEMPTS:
            logger.warning(
                "🚨 Error %s has reached %d/%d hotfix attempts in 24h. HALTING.",
                signature, attempt_count, MAX_HOTFIX_ATTEMPTS,
            )
            return False, attempt_count

        return True, attempt_count + 1

    def record_attempt(self, signature: str):
        """Record a hotfix attempt for rate limiting."""
        if signature not in self._error_ledger:
            self._error_ledger[signature] = []
        self._error_ledger[signature].append((time.time(), len(self._error_ledger[signature]) + 1))
        self._save_ledger()

    # ────────────────────────────────────────────────
    # Ledger Persistence
    # ────────────────────────────────────────────────

    def _load_ledger(self):
        """Load the error ledger from disk."""
        ledger_path = self._hotfix_dir / "error_ledger.json"
        if ledger_path.exists():
            try:
                data = json.loads(ledger_path.read_text(encoding="utf-8"))
                self._error_ledger = {
                    k: [(ts, num) for ts, num in v]
                    for k, v in data.items()
                }
            except Exception:
                self._error_ledger = {}

    def _save_ledger(self):
        """Persist the error ledger to disk."""
        ledger_path = self._hotfix_dir / "error_ledger.json"
        try:
            ledger_path.write_text(
                json.dumps(self._error_ledger, indent=2),
                encoding="utf-8",
            )
        except Exception as exc:
            logger.warning("Could not save error ledger: %s", exc)

    # ────────────────────────────────────────────────
    # Root Cause Analysis
    # ────────────────────────────────────────────────

    async def analyze_root_cause(
        self,
        error_text: str,
        release_sha: str = "",
    ) -> Tuple[bool, Dict]:
        """
        Route the production stack trace to the Local Manager for RCA.
        Returns (success, analysis_dict).
        """
        if not self._manager:
            return False, {"error": "No Local Manager available for RCA."}

        user_prompt = (
            f"PRODUCTION ERROR (release SHA: {release_sha or 'unknown'}):\n\n"
            f"{error_text[:2500]}\n\n"
            "Perform root cause analysis."
        )

        try:
            raw = await self._manager.ask_local_model(
                system_prompt=self.ROOT_CAUSE_PROMPT,
                user_prompt=user_prompt,
                temperature=0.0,
            )

            if not raw:
                return False, {"error": "LLM returned empty response."}

            # Parse JSON
            json_match = re.search(r'\{[^}]+\}', raw, re.DOTALL)
            if json_match:
                analysis = json.loads(json_match.group())
                return True, analysis

            return False, {"error": f"Could not parse RCA response: {raw[:200]}"}

        except Exception as exc:
            return False, {"error": f"RCA failed: {exc}"}

    # ────────────────────────────────────────────────
    # Hotfix Epic Generation
    # ────────────────────────────────────────────────

    def generate_hotfix_epic(
        self,
        signature: str,
        analysis: Dict,
        release_sha: str = "",
    ) -> Tuple[bool, str]:
        """
        Write a HOTFIX_EPIC.md file from the root cause analysis.
        Returns (success, epic_path).
        """
        epic_content = self.HOTFIX_EPIC_TEMPLATE.format(
            signature=signature,
            root_cause=analysis.get("root_cause", "Unknown"),
            file=analysis.get("file", "unknown"),
            line=analysis.get("line", "?"),
            fix_description=analysis.get("fix_description", "Fix the identified bug."),
            release_sha=release_sha or "HEAD",
        )

        epic_path = self._workspace / "HOTFIX_EPIC.md"
        try:
            epic_path.write_text(epic_content, encoding="utf-8")
            logger.info("📝 Generated HOTFIX_EPIC.md for signature %s", signature)
            return True, str(epic_path)
        except Exception as exc:
            return False, f"Failed to write hotfix epic: {exc}"

    # ────────────────────────────────────────────────
    # Release SHA Checkout (Stash Dirty State)
    # ────────────────────────────────────────────────

    def prepare_hotfix_branch(self, release_sha: str) -> Tuple[bool, str]:
        """
        Stash any dirty local state and checkout the exact release SHA.
        Returns (success, message).
        """
        cwd = str(self._workspace)

        try:
            # Check for dirty state
            status_proc = subprocess.run(
                ["git", "status", "--porcelain"],
                cwd=cwd, capture_output=True, text=True, timeout=10,
            )
            is_dirty = bool(status_proc.stdout.strip())

            if is_dirty:
                # Stash local work
                stash_proc = subprocess.run(
                    ["git", "stash", "push", "-m", "telemetry-hotfix-stash"],
                    cwd=cwd, capture_output=True, text=True, timeout=10,
                )
                if stash_proc.returncode != 0:
                    return False, f"Git stash failed: {stash_proc.stderr[:200]}"
                logger.info("📦 Stashed dirty local state.")

            # Create hotfix branch from release SHA
            branch_name = f"hotfix/{release_sha[:8]}"
            checkout_proc = subprocess.run(
                ["git", "checkout", "-b", branch_name, release_sha],
                cwd=cwd, capture_output=True, text=True, timeout=10,
            )
            if checkout_proc.returncode != 0:
                # Branch might already exist, try switching
                subprocess.run(
                    ["git", "checkout", branch_name],
                    cwd=cwd, capture_output=True, text=True, timeout=10,
                )

            logger.info("🔀 Checked out hotfix branch: %s", branch_name)
            return True, branch_name

        except Exception as exc:
            return False, f"Hotfix branch setup failed: {exc}"

    def restore_working_state(self, original_branch: str = "main"):
        """Restore the working branch and pop the stash after hotfix."""
        cwd = str(self._workspace)
        try:
            subprocess.run(
                ["git", "checkout", original_branch],
                cwd=cwd, capture_output=True, text=True, timeout=10,
            )
            subprocess.run(
                ["git", "stash", "pop"],
                cwd=cwd, capture_output=True, text=True, timeout=10,
            )
            logger.info("📦 Restored working state on %s.", original_branch)
        except Exception as exc:
            logger.warning("Could not restore working state: %s", exc)

    # ────────────────────────────────────────────────
    # Webhook Ingestion
    # ────────────────────────────────────────────────

    def ingest_webhook(self, payload: Dict) -> Tuple[bool, str, str]:
        """
        Process an incoming error webhook payload.
        Returns (should_hotfix, signature, error_text).

        Expected payload format:
        {
            "error": "TypeError: Cannot read property 'id' of undefined",
            "stack_trace": "at PaymentHandler (/app/src/payments.js:42:12)...",
            "url": "https://myapp.vercel.app/api/checkout",
            "status_code": 500,
            "release_sha": "abc123def"
        }
        """
        error = payload.get("error", "")
        stack = payload.get("stack_trace", "")
        status = payload.get("status_code", 0)
        full_error = f"{error}\n{stack}" if stack else error

        # Step 1: Noise filter
        if self.is_noise(full_error):
            return False, "", "Filtered as noise."

        # Step 2: Fatal check
        if not self.is_fatal(full_error) and status < 500:
            return False, "", "Not a fatal error."

        # Step 3: Compute signature
        signature = self.compute_signature(full_error)

        # Step 4: Rate limit check
        allowed, attempt_num = self.check_rate_limit(signature)
        if not allowed:
            return False, signature, (
                f"OPERATOR ALERT: Error {signature} has exceeded "
                f"{MAX_HOTFIX_ATTEMPTS} hotfix attempts in 24h. Manual intervention required."
            )

        logger.info(
            "🔥 Fatal error ingested (sig: %s, attempt %d/%d)",
            signature, attempt_num, MAX_HOTFIX_ATTEMPTS,
        )
        return True, signature, full_error

    # ────────────────────────────────────────────────
    # Full Self-Healing Pipeline
    # ────────────────────────────────────────────────

    async def process_error(
        self,
        payload: Dict,
    ) -> Tuple[bool, str]:
        """
        Complete Ouroboros pipeline:
        1. Ingest and filter the error
        2. Rate-limit check
        3. Root cause analysis
        4. Generate HOTFIX_EPIC.md
        5. Prepare hotfix branch
        Returns (hotfix_ready, epic_path_or_message).
        """
        release_sha = payload.get("release_sha", "")

        # Step 1-2: Ingest + filter + rate limit
        should_fix, signature, error_text = self.ingest_webhook(payload)
        if not should_fix:
            return False, error_text or "Error filtered or rate-limited."

        # Step 3: Root cause analysis
        rca_ok, analysis = await self.analyze_root_cause(error_text, release_sha)
        if not rca_ok:
            return False, f"RCA failed: {analysis.get('error', 'unknown')}"

        # Step 4: Generate hotfix epic
        epic_ok, epic_path = self.generate_hotfix_epic(signature, analysis, release_sha)
        if not epic_ok:
            return False, epic_path

        # Step 5: Prepare hotfix branch
        if release_sha:
            branch_ok, branch_msg = self.prepare_hotfix_branch(release_sha)
            if not branch_ok:
                logger.warning("Could not checkout release SHA: %s", branch_msg)

        # Record the attempt
        self.record_attempt(signature)

        return True, epic_path

    # ────────────────────────────────────────────────
    # Polling Mode (alternative to webhooks)
    # ────────────────────────────────────────────────

    async def poll_vercel_logs(self) -> List[Dict]:
        """
        Poll Vercel for recent error logs.
        Returns a list of error payloads in webhook format.
        """
        token = os.getenv("DEPLOY_TOKEN", "")
        if not token:
            return []

        try:
            proc = await asyncio.create_subprocess_exec(
                "vercel", "logs", "--json", "--token", token,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=str(self._workspace),
            )
            stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=30)
            raw = stdout.decode("utf-8", errors="replace")

            payloads = []
            for line in raw.strip().split("\n"):
                try:
                    entry = json.loads(line)
                    if entry.get("type") == "error" or entry.get("statusCode", 200) >= 500:
                        payloads.append({
                            "error": entry.get("message", ""),
                            "stack_trace": entry.get("stack", ""),
                            "status_code": entry.get("statusCode", 500),
                            "url": entry.get("url", ""),
                        })
                except json.JSONDecodeError:
                    continue

            return payloads

        except Exception as exc:
            logger.warning("Vercel log polling failed: %s", exc)
            return []
